import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/providers/toast-provider";
import Navbar from "@/components/navabr/page";
import Footer from "@/components/footer/page";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background text-slate-200$ {geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        {/* <ToastProvider> */}
        <Navbar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
